apiVersion: v1
kind: ConfigMap
metadata:
  name: project1-config  #name of the project
  namespace: project1-namespace  
data:
  APP_ENV: "dev"  #environment variable for development
  APP-NAME: "Project1App"
  APP_VERSION: "1.0.0"
  LOG_LEVEL: "info"
  DB_HOST: "db.dev.local"
  DB_PORT: "5432"