apiVersion: apps/v1
kind: Deployment
metadata:
  # project name
  name: project1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project1-app
  template:
    metadata:
      labels:
        app: project1-app
    spec:
      containers:
      - name: project1-container
        image: project1-image:latest
        ports:
        - containerPort: 5000
        - containerPort: 9100 # Port for Prometheus metrics

        envFrom:
        - configMapRef:
            name: project1-config
        - secretRef:
            name: project1-secret

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

# Add liveness and readiness probes to ensure application health monitoring
# These probes help Kubernetes determine when to restart containers or stop sending traffic to unhealthy pods
#liveness and readiness probes help maintain application availability and reliability in production environments
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20 
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
           path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1

        

        
              