apiVersion: apps/v1
kind: Deployment
metadata:
  # project name
  name: project1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project1-app
  template:
    metadata:
      labels:
        app: project1-app
    spec:
      containers:
      - name: project1-container
        image: project1-image:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        env:
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: project1-config
              key: APP_MESSAGE
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: project1-secret
              key: Secrate_Key
              