apiVersion: apps/v1
kind: service
metadata:
  name: project1-service
spec:
  selector:
    app: project1-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  
  