# install ingress controller first
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.1/deploy/static/provider/cloud/deploy.yaml


appVersion: v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: example.com
      http:
        paths:  
        - pathType: Prefix
          path: /service1/(.*)
          backend:
            service:
              name: my-demo-app-service
              port:
                number: 80
