apiVersion: v1
kind: Service
metadata:
  name: my-demo-app-service
spec:
  type: NodePort
  selector:
    # Ensure this matches the label in deployment.yaml
    app: My-demo-app
  ports:
    - protocol: TCP
      port: 80
      # Ensure this matches the containerPort in deployment.yaml where the app is running
      targetPort: 8000
      nodePort: 30007  